import Header from "./_component/Header";

import "@/app/_styles/globals.css";
import { ReservationProvider } from "./_component/ReservationContext";

export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="relative
      bg-primary-950 text-primary-100 min-h-screen flex flex-col antialiased"
      >
        <Header />
        <div className=" flex-1 px-8 py-12 grid">
          <main className="max-w-7xl mx-auto w-full">
            <ReservationProvider>

            {children}
            </ReservationProvider>
            
            </main>
        </div>
      </body>
    </html>
  );
}
